version: "2"

services:

  web:
    build: .
    restart: always
    ports:
      - "8086:80"
    depends_on: 
      - db
    volumes: 
      - ./files/html/index.php:/var/www/html/index.php

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_DATABASE: sqli
      MYSQL_ROOT_PASSWORD: sqli
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]



