# 网鼎杯 2018 Comment
version: "2"

services:

  web:
    build: .
    restart: always
    ports:
      - "8085:80"
    volumes: 
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: 
      - db

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_DATABASE: comment
      MYSQL_ROOT_PASSWORD: comment
      MYSQL_USER: comment
      MYSQL_PASSWORD: comment
    volumes: 
      - ./etc/db.sql:/docker-entrypoint-initdb.d/db.sql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    
